apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      serviceAccountName: ci-service
      containers:
        - name: app
          image: app:1.0.0
          #imagePullPolicy: Always
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 10
