apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: payment
  type: LoadBalancer
  externalTrafficPolicy: Cluster
