apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: app1:1.0.2
          ports:
            - containerPort: 8081
          # resources:
          #   limits:
          #     memory: 50Mi
          #   requests:
          #     memory: 50Mi
