apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  securityContext:
    runAsNonRoot: true
  containers:
    - name: allowed
      image: busybox
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  securityContext:
    runAsNonRoot: true
  containers:
    - name: allowed_2
      image: busybox
      securityContext:
        runAsNonRoot: true
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  securityContext:
    runAsNonRoot: true
  containers:
    - name: denied
      image: busybox
      securityContext:
        runAsNonRoot: false
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
    - name: denied_2
      image: busybox
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
    - name: denied_3
      image: busybox
      securityContext:
        runAsNonRoot: false
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  securityContext:
    runAsNonRoot: false
  containers:
    - name: denied_4
      image: busybox
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  securityContext:
    runAsNonRoot: false
  containers:
    - name: denied_5
      image: busybox
      securityContext:
        runAsNonRoot: false


